### ISSUE TITLE
Calculate Delegation Amount

### ISSUE THREAD

**Issue by SameerAlHarbi** [SameerAlHarbi/sgs-khadamati-sap#14]
Hi @OsamaNajjar 

I already create new called **14-calculate-delegation-amount** branch for this issue and it's based on development branch.

please follow this step on your local development environment 

git fetch origin
git checkout 14-calculate-delegation-amount

**Comment by OsamaNajjar** [comment]
Hi @SameerAlHarbi  

Sure I'm working now for this issue
