### ISSUE TITLE
Delegation projects

### ISSUE THREAD

**Issue by SameerAlHarbi** [SameerAlHarbi/sgs-khadamati-sap#9]
Hi @OsamaNajjar  Please we need to add the delegation projects sap functions

**Comment by OsamaNajjar** [comment]
sure

**Comment by OsamaNajjar** [comment]
dear @SameerAlHarbi 

please reviw new code for Delegation Projects

**Comment by OsamaNajjar** [comment]
Hi @SameerAlHarbi 

please review new update
